model_params:  
  descrip: "End to End using AOD. Varied trans map."
  model_name: "AOD" # DD or MSCNN or AOD
  mode: "test"   # train or test
  log_dir: /media/mnt/dehaze/aod_logs/ # path to write the model and load the model

training_params:
  learning_rate: 1e-04
  epochs: 100
  batch_size: 32
  # data_path: /media/mnt/dehaze/data/ChinaMM18dehaze/  # Path from where to load the data
  data_path: /media/mnt/dehaze/data/cityscape/processed/
